name: movies_desafio_5
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  dartz:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  uno: ^1.0.1+3
  google_fonts: ^3.0.1
  mocktail: ^0.3.0
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true